/**
 * NVIDIA API Provider Adapter for pi
 *
 * Dynamically registers NVIDIA models generated via `bun run update-models`
 * and resolves thinking configuration.
 */

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type {
	Api,
	AssistantMessageEventStream,
	Context,
	Model,
	SimpleStreamOptions,
} from "@earendil-works/pi-ai";
import { streamSimpleOpenAICompletions } from "@earendil-works/pi-ai";
import { getAgentDir, type ExtensionAPI } from "@earendil-works/pi-coding-agent";

// Load autogenerated configs
import modelsData from "./src/generated/models.json";

// =============================================================================
// Constants
// =============================================================================
const NVIDIA_NIM_BASE_URL = "https://integrate.api.nvidia.com/v1";
const NVIDIA_NIM_API_KEY_ENV = "NVIDIA_NIM_API_KEY";
const NVIDIA_API_KEY_ENV = "NVIDIA_API_KEY";
const NVIDIA_API_KEY_ENV_NAMES = [NVIDIA_NIM_API_KEY_ENV, NVIDIA_API_KEY_ENV] as const;
const PROVIDER_NAME = "nvidia-nim";

// =============================================================================
// Types
// =============================================================================
interface NimModelEntry {
	id: string;
	name: string;
	company: string;
	reasoning: boolean;
	input: ("text" | "image")[];
	contextWindow: number;
	maxTokens: number;
	cost: { input: number; output: number; cacheRead: number; cacheWrite: number };
	compat?: Record<string, any>;
	releaseDate?: string;
	lastUpdated?: string;
}

interface ThinkingConfig {
	enableKwargs: Record<string, any>;
	disableKwargs?: Record<string, any>;
	sendReasoningEffort?: boolean;
	includeReasoningEffortInKwargs?: boolean;
}

// =============================================================================
// API Key Resolution
// =============================================================================
type NimApiKeyEnvName = (typeof NVIDIA_API_KEY_ENV_NAMES)[number];
type AuthStorageLike = {
	get?: (provider: string) => unknown;
};

interface NimApiKeyCredential {
	type: "api_key";
	key: string;
}

function getNimApiKeyEnv(): NimApiKeyEnvName | undefined {
	return NVIDIA_API_KEY_ENV_NAMES.find((envName) => !!process.env[envName]);
}

function getNimApiKey(): string | undefined {
	const envName = getNimApiKeyEnv();
	const apiKey = envName ? process.env[envName] : undefined;
	return apiKey?.trim() || undefined;
}

function getNimProviderApiKeyConfig(): string {
	return `$${getNimApiKeyEnv() ?? NVIDIA_NIM_API_KEY_ENV}`;
}

function isNimApiKeyEnvName(value: string): value is NimApiKeyEnvName {
	return NVIDIA_API_KEY_ENV_NAMES.includes(value as NimApiKeyEnvName);
}

function isNimApiKeyEnvReference(value: string): boolean {
	return value.startsWith("$") && isNimApiKeyEnvName(value.slice(1));
}

function isNimApiKeyEnvPlaceholder(value: string): boolean {
	return isNimApiKeyEnvName(value) || isNimApiKeyEnvReference(value);
}

function resolveNimApiKeyEnvReference(value: string): string | undefined {
	if (!isNimApiKeyEnvReference(value)) return undefined;
	const envValue = process.env[value.slice(1)]?.trim();
	return envValue || undefined;
}

function isNimApiKeyEnvValue(value: string): boolean {
	return NVIDIA_API_KEY_ENV_NAMES.some((envName) => process.env[envName]?.trim() === value);
}

function isNimApiKeyCredential(credential: unknown): credential is NimApiKeyCredential {
	return (
		typeof credential === "object" &&
		credential !== null &&
		(credential as { type?: unknown }).type === "api_key" &&
		typeof (credential as { key?: unknown }).key === "string"
	);
}

function readStoredNimApiKeyConfig(): string | undefined {
	try {
		const authPath = join(getAgentDir(), "auth.json");
		if (!existsSync(authPath)) return undefined;
		const data = JSON.parse(readFileSync(authPath, "utf-8")) as Record<string, unknown>;
		const credential = data[PROVIDER_NAME];
		return isNimApiKeyCredential(credential) ? credential.key : undefined;
	} catch {
		return undefined;
	}
}

function getStoredNimApiKeyConfig(authStorage?: AuthStorageLike): string | undefined {
	if (authStorage) {
		try {
			const credential = authStorage.get?.(PROVIDER_NAME);
			return isNimApiKeyCredential(credential) ? credential.key : undefined;
		} catch {
			return undefined;
		}
	}
	return readStoredNimApiKeyConfig();
}

function hasStoredNimCommandCredential(authStorage?: AuthStorageLike): boolean {
	return getStoredNimApiKeyConfig(authStorage)?.startsWith("!") ?? false;
}

function getStoredResolvedNimApiKey(authStorage?: AuthStorageLike): string | undefined {
	const configuredApiKey = getStoredNimApiKeyConfig(authStorage)?.trim();
	if (!configuredApiKey || configuredApiKey.startsWith("!")) return undefined;
	const envValue = process.env[configuredApiKey]?.trim();
	return envValue || configuredApiKey;
}

function normalizeResolvedNimApiKey(apiKey: string | undefined): string | undefined {
	if (apiKey === undefined) return undefined;
	const trimmed = apiKey.trim();
	if (!trimmed) {
		throw new Error("NVIDIA NIM API key resolved to an empty value.");
	}
	return trimmed;
}

function resolveNimApiKey(apiKey: string | undefined, authStorage?: AuthStorageLike): string | undefined {
	const resolvedApiKey = normalizeResolvedNimApiKey(apiKey);
	const hasStoredCommandCredential = hasStoredNimCommandCredential(authStorage);

	if (
		hasStoredCommandCredential &&
		(!resolvedApiKey || isNimApiKeyEnvPlaceholder(resolvedApiKey) || isNimApiKeyEnvValue(resolvedApiKey))
	) {
		throw new Error("NVIDIA NIM API key command resolved to an empty value.");
	}

	const storedApiKey = getStoredResolvedNimApiKey(authStorage);
	if (storedApiKey && (!resolvedApiKey || isNimApiKeyEnvPlaceholder(resolvedApiKey))) return storedApiKey;

	if (resolvedApiKey) {
		const envReferenceApiKey = resolveNimApiKeyEnvReference(resolvedApiKey);
		if (envReferenceApiKey) return envReferenceApiKey;
		if (!isNimApiKeyEnvPlaceholder(resolvedApiKey)) return resolvedApiKey;
	}

	return getNimApiKey();
}

function resolveRequiredNimApiKey(apiKey: string | undefined): string {
	const resolvedApiKey = resolveNimApiKey(apiKey);
	if (resolvedApiKey) return resolvedApiKey;
	throw new Error(
		`NVIDIA NIM: no API key configured. Set ${NVIDIA_NIM_API_KEY_ENV} or ${NVIDIA_API_KEY_ENV}. ` +
		`Get a free API key at https://build.nvidia.com and export it: ` +
		`export ${NVIDIA_NIM_API_KEY_ENV}=nvapi-...`,
	);
}

// =============================================================================
// Streaming Handler
// =============================================================================
function mapNimTopLevelReasoning(reasoning: SimpleStreamOptions["reasoning"]): SimpleStreamOptions["reasoning"] {
	if (reasoning === "minimal") return "low";
	if (reasoning === "xhigh") return "high";
	return reasoning;
}

function mapDeepSeekV4Reasoning(reasoning: SimpleStreamOptions["reasoning"]): "high" | "max" {
	return reasoning === "xhigh" ? "max" : "high";
}

function buildThinkingKwargs(
	thinkingConfig: ThinkingConfig,
	reasoning: SimpleStreamOptions["reasoning"],
): Record<string, unknown> {
	const kwargs = { ...thinkingConfig.enableKwargs };
	if (thinkingConfig.includeReasoningEffortInKwargs) {
		kwargs.reasoning_effort = mapDeepSeekV4Reasoning(reasoning);
	}
	return kwargs;
}

function buildNimRequestHeaders(headers: SimpleStreamOptions["headers"], apiKey: string): Record<string, string> {
	const resolvedHeaders: Record<string, string> = {};
	for (const [key, value] of Object.entries(headers ?? {})) {
		if (key.toLowerCase() === "authorization") continue;
		resolvedHeaders[key] = value as string;
	}
	return {
		...resolvedHeaders,
		Authorization: `Bearer ${apiKey}`,
	};
}

function nimStreamSimple(
	model: Model<Api>,
	context: Context,
	options?: SimpleStreamOptions,
): AssistantMessageEventStream {
	if (model.provider !== PROVIDER_NAME) {
		return streamSimpleOpenAICompletions(model as Model<"openai-completions">, context, options);
	}

	const thinkingConfig = (modelsData.thinkingConfigs as Record<string, ThinkingConfig>)[model.id];
	const reasoning = options?.reasoning;
	const isThinkingEnabled = !!reasoning;
	const mappedReasoning = mapNimTopLevelReasoning(reasoning);

	let effectiveReasoning = mappedReasoning;
	if (thinkingConfig && isThinkingEnabled && !thinkingConfig.sendReasoningEffort) {
		effectiveReasoning = undefined;
	}

	const nimApiKey = resolveRequiredNimApiKey(options?.apiKey);

	const modifiedOptions: SimpleStreamOptions = {
		...options,
		reasoning: effectiveReasoning,
		apiKey: nimApiKey,
		headers: buildNimRequestHeaders(options?.headers, nimApiKey),
		onPayload: (params: unknown) => {
			const p = params as Record<string, unknown>;

			if (thinkingConfig) {
				if (isThinkingEnabled) {
					p.chat_template_kwargs = buildThinkingKwargs(thinkingConfig, reasoning);
				} else if (thinkingConfig.disableKwargs) {
					p.chat_template_kwargs = thinkingConfig.disableKwargs;
				}
			}

			if (p.reasoning_effort === "minimal") {
				p.reasoning_effort = "low";
			}

			// Clean array text contents for models expecting plain string
			const messages = p.messages as Array<Record<string, unknown>> | undefined;
			if (messages) {
				for (const msg of messages) {
					if (Array.isArray(msg.content)) {
						const parts = msg.content as Array<Record<string, unknown>>;
						const allText = parts.every((part) => part.type === "text");
						if (allText) {
							msg.content = parts.map((part) => part.text as string).join("\n");
						}
					}
				}
			}

			return options?.onPayload?.(params, model);
		},
	};

	return streamSimpleOpenAICompletions(model as Model<"openai-completions">, context, modifiedOptions);
}

// =============================================================================
// Heuristic Model Builder (Fallback for newly released models in session_start)
// =============================================================================
function makeDisplayName(modelId: string): string {
	const parts = modelId.split("/");
	const name = parts[parts.length - 1];
	return name
		.replace(/-/g, " ")
		.replace(/_/g, " ")
		.replace(/\b\w/g, (c) => c.toUpperCase());
}

function buildModelEntryFallback(modelId: string): NimModelEntry {
	const lowerId = modelId.toLowerCase();
	
	// Heuristics mapping
	const reasoning = lowerId.includes("r1") ||
		lowerId.includes("reasoning") ||
		lowerId.includes("thinking") ||
		lowerId.includes("qwq") ||
		(lowerId.includes("glm") && !lowerId.includes("glm4.7"));

	const isVision = lowerId.includes("vision") || lowerId.includes("-vl") || lowerId.includes("multimodal");

	let contextWindow = 128000;
	if (lowerId.includes("1m") || lowerId.includes("1024k")) contextWindow = 1048576;
	else if (lowerId.includes("8k")) contextWindow = 8192;
	else if (lowerId.includes("32k")) contextWindow = 32768;
	else if (lowerId.includes("64k")) contextWindow = 65536;
	else if (lowerId.includes("4096") || lowerId.includes("4k")) contextWindow = 4096;

	let maxTokens = contextWindow >= 128000 ? 16384 : Math.min(4096, contextWindow);

	const compat: Record<string, any> = {
		supportsReasoningEffort: false,
		supportsDeveloperRole: false,
		maxTokensField: "max_tokens",
	};

	if (modelId.startsWith("mistralai/")) {
		compat.requiresToolResultName = true;
		compat.requiresThinkingAsText = true;
		compat.requiresMistralToolIds = true;
	}

	return {
		id: modelId,
		name: makeDisplayName(modelId),
		company: modelId.split("/")[0] || "other",
		reasoning,
		input: isVision ? ["text", "image"] : ["text"],
		contextWindow,
		maxTokens,
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		compat,
	};
}

// Embedded / non-chat models to skip
const SKIP_PATTERNS = [
	/embed/,
	/clip/,
	/streampetr/,
	/vila/,
	/retriever/,
	/reward/,
	/safety/,
	/guard/,
	/deplot/,
	/paligemma/,
	/translate/,
	/kosmos-2/,
	/fuyu-8b/,
	/starcoder2/
];

function shouldSkipModel(modelId: string): boolean {
	const lowerId = modelId.toLowerCase();
	return SKIP_PATTERNS.some((pattern) => pattern.test(lowerId));
}

// =============================================================================
// Live Discovery
// =============================================================================
interface NimApiModel {
	id: string;
	object: string;
	owned_by: string;
}

type NimModelFetchResult =
	| { ok: true; modelIds: string[] }
	| { ok: false; reason: "auth" | "transient" | "invalid" | "network" | "other" };

const NIM_DISCOVERY_CREDENTIAL_WARNING =
	"NVIDIA Adapter model discovery skipped: check your credentials.";

function sanitizeNimLogMessage(message: string): string {
	return message.replace(/nvapi-[A-Za-z0-9._-]+/g, "nvapi-[REDACTED]");
}

function notifyNimDiscoveryCredentialWarning(ctx: any): void {
	ctx?.ui?.notify?.(NIM_DISCOVERY_CREDENTIAL_WARNING, "warning");
}

async function resolveNimDiscoveryApiKey(ctx: any): Promise<string | undefined> {
	try {
		const apiKey = await ctx?.modelRegistry?.getApiKeyForProvider?.(PROVIDER_NAME);
		return resolveNimApiKey(apiKey, ctx?.modelRegistry?.authStorage);
	} catch (error) {
		const message = error instanceof Error ? error.message : String(error);
		console.warn(`pi-nvidia-adapter: ${sanitizeNimLogMessage(message)}`);
		notifyNimDiscoveryCredentialWarning(ctx);
		return undefined;
	}
}

async function fetchNimModels(apiKey: string): Promise<NimModelFetchResult> {
	try {
		const response = await fetch(`${NVIDIA_NIM_BASE_URL}/models`, {
			headers: {
				Authorization: `Bearer ${apiKey}`,
				Accept: "application/json",
			},
			signal: AbortSignal.timeout(10000),
		});

		if (response.status === 401 || response.status === 403) {
			return { ok: false, reason: "auth" };
		}
		if (response.status === 429 || response.status >= 500) {
			return { ok: false, reason: "transient" };
		}
		if (!response.ok) return { ok: false, reason: "other" };

		const data = (await response.json()) as { data?: NimApiModel[] };
		if (!Array.isArray(data.data)) return { ok: false, reason: "invalid" };

		return {
			ok: true,
			modelIds: data.data.map((m) => m.id).filter((id): id is string => typeof id === "string" && id.length > 0),
		};
	} catch {
		return { ok: false, reason: "network" };
	}
}

// =============================================================================
// Extension Entry Point
// =============================================================================
export default function (pi: ExtensionAPI) {
	const providerApiKeyConfig = getNimProviderApiKeyConfig();

	// Load built-in models
	const modelMap = new Map<string, NimModelEntry>();
	for (const m of modelsData.models) {
		modelMap.set(m.id, m as NimModelEntry);
	}

	pi.registerProvider(PROVIDER_NAME, {
		baseUrl: NVIDIA_NIM_BASE_URL,
		apiKey: providerApiKeyConfig,
		api: "openai-completions",
		authHeader: true,
		models: Array.from(modelMap.values()),
		streamSimple: nimStreamSimple,
	});

	// Session Start: Incremental discovery
	pi.on("session_start", async (_event: any, ctx: any) => {
		const apiKey = await resolveNimDiscoveryApiKey(ctx);
		if (!apiKey) return;

		const fetchResult = await fetchNimModels(apiKey);
		if (!fetchResult.ok) {
			if (fetchResult.reason === "auth") {
				notifyNimDiscoveryCredentialWarning(ctx);
			}
			return;
		}

		let newModelsAdded = 0;
		for (const id of fetchResult.modelIds) {
			if (modelMap.has(id)) continue;
			if (shouldSkipModel(id)) continue;

			const entry = buildModelEntryFallback(id);
			modelMap.set(id, entry);
			newModelsAdded++;
		}

		if (newModelsAdded > 0) {
			ctx.modelRegistry.registerProvider(PROVIDER_NAME, {
				baseUrl: NVIDIA_NIM_BASE_URL,
				apiKey: getNimProviderApiKeyConfig(),
				api: "openai-completions",
				authHeader: true,
				models: Array.from(modelMap.values()),
				streamSimple: nimStreamSimple,
			});
		}
	});
}
