/**
 * NVIDIA API Provider Adapter for pi
 *
 * Dynamically registers NVIDIA models generated via `bun run update-models`
 * and resolves thinking configuration.
 */

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type {
	Api,
	AssistantMessageEventStream,
	Context,
	Model,
	SimpleStreamOptions,
} from "@earendil-works/pi-ai";
import { streamSimpleOpenAICompletions } from "@earendil-works/pi-ai";
import { getAgentDir, type ExtensionAPI } from "@earendil-works/pi-coding-agent";

// Load shared module
import type { NimModelEntry } from "./src/shared";

// Load autogenerated configs
import modelsData from "./src/generated/models.json";

// =============================================================================
// Constants
// =============================================================================
const NVIDIA_NIM_BASE_URL = "https://integrate.api.nvidia.com/v1";
const NVIDIA_NIM_API_KEY_ENV = "NVIDIA_NIM_API_KEY";
const NVIDIA_API_KEY_ENV = "NVIDIA_API_KEY";
const NVIDIA_API_KEY_ENV_NAMES = [NVIDIA_NIM_API_KEY_ENV, NVIDIA_API_KEY_ENV] as const;
const PROVIDER_NAME = "nvidia-nim";

// =============================================================================
// Types
// =============================================================================
interface ThinkingConfig {
	enableKwargs: Record<string, any>;
	disableKwargs?: Record<string, any>;
	sendReasoningEffort?: boolean;
	includeReasoningEffortInKwargs?: boolean;
}

// =============================================================================
// API Key Resolution
// =============================================================================
type NimApiKeyEnvName = (typeof NVIDIA_API_KEY_ENV_NAMES)[number];
type AuthStorageLike = {
	get?: (provider: string) => unknown;
};

interface NimApiKeyCredential {
	type: "api_key";
	key: string;
}

function getNimApiKeyEnv(): NimApiKeyEnvName | undefined {
	return NVIDIA_API_KEY_ENV_NAMES.find((envName) => !!process.env[envName]);
}

function getNimApiKey(): string | undefined {
	const envName = getNimApiKeyEnv();
	const apiKey = envName ? process.env[envName] : undefined;
	return apiKey?.trim() || undefined;
}

function getNimProviderApiKeyConfig(): string {
	return `$${getNimApiKeyEnv() ?? NVIDIA_NIM_API_KEY_ENV}`;
}

function isNimApiKeyEnvName(value: string): value is NimApiKeyEnvName {
	return NVIDIA_API_KEY_ENV_NAMES.includes(value as NimApiKeyEnvName);
}

function isNimApiKeyEnvReference(value: string): boolean {
	return value.startsWith("$") && isNimApiKeyEnvName(value.slice(1));
}

function isNimApiKeyEnvPlaceholder(value: string): boolean {
	return isNimApiKeyEnvName(value) || isNimApiKeyEnvReference(value);
}

function resolveNimApiKeyEnvReference(value: string): string | undefined {
	if (!isNimApiKeyEnvReference(value)) return undefined;
	const envValue = process.env[value.slice(1)]?.trim();
	return envValue || undefined;
}

function isNimApiKeyEnvValue(value: string): boolean {
	return NVIDIA_API_KEY_ENV_NAMES.some((envName) => process.env[envName]?.trim() === value);
}

function isNimApiKeyCredential(credential: unknown): credential is NimApiKeyCredential {
	return (
		typeof credential === "object" &&
		credential !== null &&
		(credential as { type?: unknown }).type === "api_key" &&
		typeof (credential as { key?: unknown }).key === "string"
	);
}

function readStoredNimApiKeyConfig(): string | undefined {
	try {
		const authPath = join(getAgentDir(), "auth.json");
		if (!existsSync(authPath)) return undefined;
		const data = JSON.parse(readFileSync(authPath, "utf-8")) as Record<string, unknown>;
		const credential = data[PROVIDER_NAME];
		return isNimApiKeyCredential(credential) ? credential.key : undefined;
	} catch {
		return undefined;
	}
}

function getStoredNimApiKeyConfig(authStorage?: AuthStorageLike): string | undefined {
	if (authStorage) {
		try {
			const credential = authStorage.get?.(PROVIDER_NAME);
			return isNimApiKeyCredential(credential) ? credential.key : undefined;
		} catch {
			return undefined;
		}
	}
	return readStoredNimApiKeyConfig();
}

function hasStoredNimCommandCredential(authStorage?: AuthStorageLike): boolean {
	return getStoredNimApiKeyConfig(authStorage)?.startsWith("!") ?? false;
}

function getStoredResolvedNimApiKey(authStorage?: AuthStorageLike): string | undefined {
	const configuredApiKey = getStoredNimApiKeyConfig(authStorage)?.trim();
	if (!configuredApiKey || configuredApiKey.startsWith("!")) return undefined;
	const envValue = process.env[configuredApiKey]?.trim();
	return envValue || configuredApiKey;
}

function normalizeResolvedNimApiKey(apiKey: string | undefined): string | undefined {
	if (apiKey === undefined) return undefined;
	const trimmed = apiKey.trim();
	if (!trimmed) {
		throw new Error("NVIDIA NIM API key resolved to an empty value.");
	}
	return trimmed;
}

function resolveNimApiKey(apiKey: string | undefined, authStorage?: AuthStorageLike): string | undefined {
	const resolvedApiKey = normalizeResolvedNimApiKey(apiKey);
	const hasStoredCommandCredential = hasStoredNimCommandCredential(authStorage);

	if (
		hasStoredCommandCredential &&
		(!resolvedApiKey || isNimApiKeyEnvPlaceholder(resolvedApiKey) || isNimApiKeyEnvValue(resolvedApiKey))
	) {
		throw new Error("NVIDIA NIM API key command resolved to an empty value.");
	}

	const storedApiKey = getStoredResolvedNimApiKey(authStorage);
	if (storedApiKey && (!resolvedApiKey || isNimApiKeyEnvPlaceholder(resolvedApiKey))) return storedApiKey;

	if (resolvedApiKey) {
		const envReferenceApiKey = resolveNimApiKeyEnvReference(resolvedApiKey);
		if (envReferenceApiKey) return envReferenceApiKey;
		if (!isNimApiKeyEnvPlaceholder(resolvedApiKey)) return resolvedApiKey;
	}

	return getNimApiKey();
}

function resolveRequiredNimApiKey(apiKey: string | undefined): string {
	const resolvedApiKey = resolveNimApiKey(apiKey);
	if (resolvedApiKey) return resolvedApiKey;
	throw new Error(
		`NVIDIA NIM: no API key configured. Set ${NVIDIA_NIM_API_KEY_ENV} or ${NVIDIA_API_KEY_ENV}. ` +
		`Get a free API key at https://build.nvidia.com and export it: ` +
		`export ${NVIDIA_NIM_API_KEY_ENV}=nvapi-...`,
	);
}

// =============================================================================
// Streaming Handler
// =============================================================================
function mapNimTopLevelReasoning(reasoning: SimpleStreamOptions["reasoning"]): SimpleStreamOptions["reasoning"] {
	if (reasoning === "minimal") return "low";
	if (reasoning === "xhigh") return "high";
	return reasoning;
}

function mapReasoningEffortToValue(reasoning: SimpleStreamOptions["reasoning"]): "high" | "max" {
	return reasoning === "xhigh" ? "max" : "high";
}

function buildThinkingKwargs(
	thinkingConfig: ThinkingConfig,
	reasoning: SimpleStreamOptions["reasoning"],
): Record<string, unknown> {
	const kwargs = { ...thinkingConfig.enableKwargs };
	if (thinkingConfig.includeReasoningEffortInKwargs) {
		kwargs.reasoning_effort = mapReasoningEffortToValue(reasoning);
	}
	return kwargs;
}

function buildNimRequestHeaders(headers: SimpleStreamOptions["headers"], apiKey: string): Record<string, string> {
	const resolvedHeaders: Record<string, string> = {};
	for (const [key, value] of Object.entries(headers ?? {})) {
		if (key.toLowerCase() === "authorization") continue;
		resolvedHeaders[key] = value as string;
	}
	return {
		...resolvedHeaders,
		Authorization: `Bearer ${apiKey}`,
	};
}

function nimStreamSimple(
	model: Model<Api>,
	context: Context,
	options?: SimpleStreamOptions,
): AssistantMessageEventStream {
	if (model.provider !== PROVIDER_NAME) {
		return streamSimpleOpenAICompletions(model as Model<"openai-completions">, context, options);
	}

	const thinkingConfig = (modelsData.thinkingConfigs as Record<string, ThinkingConfig>)[model.id];
	const reasoning = options?.reasoning;
	const isThinkingEnabled = !!reasoning;
	const mappedReasoning = mapNimTopLevelReasoning(reasoning);

	let effectiveReasoning = mappedReasoning;
	if (thinkingConfig && isThinkingEnabled && !thinkingConfig.sendReasoningEffort) {
		effectiveReasoning = undefined;
	}

	const nimApiKey = resolveRequiredNimApiKey(options?.apiKey);

	const modifiedOptions: SimpleStreamOptions = {
		...options,
		reasoning: effectiveReasoning,
		apiKey: nimApiKey,
		headers: buildNimRequestHeaders(options?.headers, nimApiKey),
		onPayload: (params: unknown) => {
			const p = params as Record<string, unknown>;

			if (thinkingConfig) {
				if (isThinkingEnabled) {
					p.chat_template_kwargs = buildThinkingKwargs(thinkingConfig, reasoning);
				} else if (thinkingConfig.disableKwargs) {
					p.chat_template_kwargs = thinkingConfig.disableKwargs;
				}
			}

			if (p.reasoning_effort === "minimal") {
				p.reasoning_effort = "low";
			}

			// Clean array text contents for models expecting plain string
			const messages = p.messages as Array<Record<string, unknown>> | undefined;
			if (messages) {
				for (const msg of messages) {
					if (Array.isArray(msg.content)) {
						const parts = msg.content as Array<Record<string, unknown>>;
						const allText = parts.every((part) => part.type === "text");
						if (allText) {
							msg.content = parts.map((part) => part.text as string).join("\n");
						}
					}
				}
			}

			return options?.onPayload?.(params, model);
		},
	};

	return streamSimpleOpenAICompletions(model as Model<"openai-completions">, context, modifiedOptions);
}

// =============================================================================
// Extension Entry Point
// =============================================================================
export default function (pi: ExtensionAPI) {
	const providerApiKeyConfig = getNimProviderApiKeyConfig();

	// Load built-in models from statically generated modelsData JSON
	const modelMap = new Map<string, NimModelEntry>();
	for (const m of modelsData.models) {
		modelMap.set(m.id, m as NimModelEntry);
	}

	pi.registerProvider(PROVIDER_NAME, {
		baseUrl: NVIDIA_NIM_BASE_URL,
		apiKey: providerApiKeyConfig,
		api: "openai-completions",
		authHeader: true,
		models: Array.from(modelMap.values()),
		streamSimple: nimStreamSimple,
	});
}
